#!/usr/bin/env python3
"""Generate chromium-150.0.7871.222-250.patch.

Google published no release tarball for 150.0.7871.250, the Chromium that
Electron 43.7.0 pins; the newest 150 tarball is 150.0.7871.222. This builds the
exact upstream difference between the two tags -- chromium/src plus the four
DEPS-pinned subprojects whose revision moved -- filtered to what the -lite
tarball actually contains, and dry-runs it against a pristine .222 tree.
"""
import hashlib
import os
import subprocess
import sys

W = "/var/tmp/electron-work"
TREE = W + "/pristine/chromium-150.0.7871.222"
D = W + "/delta"
OUT = D + "/chromium-150.0.7871.222-250.patch"

SOURCES = [
    ("src.diff", "", "chromium/src", "150.0.7871.222", "150.0.7871.250",
     "https://github.com/chromium/chromium/compare/150.0.7871.222...150.0.7871.250.diff"),
    ("v8.diff", "v8/", "v8", "ffb169e1399da5270302935da24ed1f95746ae0d",
     "c6e16522def1bf4dc2c91e54f5bfffa459168417",
     "https://chromium.googlesource.com/v8/v8/+/{old}..{new}/?format=TEXT"),
    ("angle.diff", "third_party/angle/", "angle", "674c1eb24c1250ddf5911ac46b5373cd084d4e78",
     "c5bf49e78850a5335a8fa2a7bfb53b559fbfc927",
     "https://chromium.googlesource.com/angle/angle/+/{old}..{new}/?format=TEXT"),
    ("dawn.diff", "third_party/dawn/", "dawn", "d089fc91e7e4881362463faf8efe9ae435e34660",
     "b8cea1289d76a80e877e0d751ef3a35088256e89",
     "https://dawn.googlesource.com/dawn/+/{old}..{new}/?format=TEXT"),
    ("skia.diff", "third_party/skia/", "skia", "a81173f17b197686dc1e6c78515de86e92ddc861",
     "9c7b2dffb2433f5a0cc2b77f06025a09126807ed",
     "https://skia.googlesource.com/skia/+/{old}..{new}/?format=TEXT"),
]


def blocks(text):
    cur = []
    for line in text.split("\n"):
        if line.startswith("diff --git ") and cur:
            yield cur
            cur = []
        if cur or line.startswith("diff --git "):
            cur.append(line)
    if cur:
        yield cur


def rewrite(block, prefix):
    out = []
    in_header = True
    for line in block:
        if in_header:
            if line.startswith("@@"):
                in_header = False
            elif line.startswith("diff --git a/"):
                a, b = line[len("diff --git a/"):].rsplit(" b/", 1)
                line = "diff --git a/%s%s b/%s%s" % (prefix, a, prefix, b)
            elif line.startswith("--- a/"):
                line = "--- a/" + prefix + line[len("--- a/"):]
            elif line.startswith("+++ b/"):
                line = "+++ b/" + prefix + line[len("+++ b/"):]
            elif line.startswith(("rename from ", "rename to ", "copy from ", "copy to ")):
                k, v = line.split(" ", 2)[:2], line.split(" ", 2)[2]
                line = "%s %s %s%s" % (k[0], k[1], prefix, v)
        out.append(line)
    return out


header = [
    "chromium 150.0.7871.222 -> 150.0.7871.250 (the Chromium Electron 43.7.0 pins)",
    "",
    "LOCAL WORKAROUND (source plumbing, no code of ours). Google published no",
    "release tarball for 150.0.7871.250; the newest 150 tarball is .222. This is",
    "the verbatim upstream difference between the two tags, generated by",
    "omarchy-ppc64le's reference/chromium-150/mkdelta.py from:",
    "",
]
kept_lines = []
summary = []
for fname, prefix, repo, old, new, url in SOURCES:
    text = open(os.path.join(D, fname), encoding="utf-8", errors="surrogateescape").read()
    n = kept = gitlink = absent = 0
    for blk in blocks(text):
        n += 1
        body = "\n".join(blk[:8])
        path = blk[0].rsplit(" b/", 1)[1]
        full = os.path.join(TREE, prefix + path)
        if "Subproject commit" in body:
            gitlink += 1          # DEPS revision bumps; the subproject diff follows
            continue
        is_new = any(l.startswith("new file mode") for l in blk[1:4])
        if is_new:
            if not os.path.isdir(os.path.dirname(full)):
                absent += 1       # new file under a directory the -lite tarball omits
                continue
        elif not os.path.exists(full):
            absent += 1           # ios/, android translations, v8 test status
            continue
        kept += 1
        kept_lines += rewrite(blk, prefix)
    header.append("  %-13s %s..%s" % (repo, old, new))
    header.append("                %s" % url.format(old=old, new=new))
    summary.append("%s: %d file diffs, kept %d, dropped %d DEPS gitlinks and %d paths the -lite tarball omits"
                   % (repo, n, kept, gitlink, absent))
header += [""] + ["  " + s for s in summary] + ["", ""]

with open(OUT, "w", encoding="utf-8", errors="surrogateescape") as f:
    f.write("\n".join(header))
    f.write("\n".join(kept_lines))
    if not kept_lines[-1] == "":
        f.write("\n")

print("\n".join(summary))
print(OUT, os.path.getsize(OUT), "bytes",
      hashlib.sha256(open(OUT, "rb").read()).hexdigest())
r = subprocess.run(["patch", "-p1", "--dry-run", "-d", TREE, "-i", OUT],
                   capture_output=True, text=True)
bad = [l for l in r.stdout.splitlines() if "FAILED" in l or "offset" in l or "fuzz" in l or "reject" in l]
print("dry-run rc=%d; %d patched-file lines; problems:" % (r.returncode, r.stdout.count("checking file")))
print("\n".join(bad) or "  none")
if r.returncode:
    print(r.stdout[-3000:], r.stderr[-2000:])
sys.exit(r.returncode)
